### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by joaovitorzktz** [0xLuca/vexternal#2]
Hello Dude I Putted My Bypass In This Project And Updated The Offsets But Esp Not Work , He Get`s The Base Of Game And All But Not Work

**Comment by egssy0** [comment]
Who’s he?

**Comment by 0xLuca** [comment]
As you can see here
https://www.unknowncheats.me/forum/3179441-post13.html,
here https://www.unknowncheats.me/forum/3179501-post17.html
or here https://www.unknowncheats.me/forum/3179530-post20.html

The problem is in your way to r/w, not in the cheat.
