### ISSUE TITLE
How to compile ? 

### ISSUE THREAD

**Issue by ertugrul-cakici** [0xLuca/vexternal#3]
Can anyone teach me how can i compile it ? I have visualt studio 2019 and c++ extensions but since I run .sln file and click the debug it says an error occured.

**Comment by getme0ut** [comment]
> Can anyone teach me how can i compile it ? I have visualt studio 2019 and c++ extensions but since I run .sln file and click the debug it says an error occured.

Compile this source: https://github.com/getme0ut/E-Valorant without errors.

**Comment by 0xLuca** [comment]
> 
> 
> Can anyone teach me how can i compile it ? I have visualt studio 2019 and c++ extensions but since I run .sln file and click the debug it says an error occured.

Which error? Please send me the error message

**Comment by getme0ut** [comment]
> Can anyone teach me how can i compile it ? I have visualt studio 2019 and c++ extensions but since I run .sln file and click the debug it says an error occured.

Here is a modified source code: https://github.com/getme0ut/E-Valorant (no errors)

**Comment by getme0ut** [comment]
> > Can anyone teach me how can i compile it ? I have visualt studio 2019 and c++ extensions but since I run .sln file and click the debug it says an error occured.
> 
> Which error? Please send me the error message

I think he's talking about errors in line 253

**Comment by Pworsay** [comment]
Could not get base address.
Press any key to continue . . .
how do i solve this problem?

**Comment by 0xLuca** [comment]
> 
> 
> Could not get base address.
> Press any key to continue . . .
> how do i solve this problem?

You have to add your own memory r/w code. Dont use the one from @getme0ut, its detected and will get you banned.
