### ISSUE TITLE
could not get base adress

### ISSUE THREAD

**Issue by bowthawsom66** [0xLuca/vexternal#5]
when I run vexternal.exe it says it cannot get base adress anyone help?

**Comment by 0xLuca** [comment]
Are you sure you added your own memory r/w code?

**Comment by bowthawsom66** [comment]
I did not. Can you please send an example on how to do that?

**Comment by vk-nom** [comment]
do it yourself lmfao

**Comment by coolkid5** [comment]
help me plz
